FROM nginx:latest

# Overwrite our configuration file to default one
COPY ./default.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html/*

COPY ./namshy_frontend/build /usr/share/nginx/html/